sudo: false
# dist: trusty
language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - libmunge-dev
      - libgenders0-dev
      - genders
      - clang-3.8
      - gcc-6

cache:
  directories:
  - $HOME/local
  - $HOME/.local

env:
  - CC=gcc
  - CC=clang
  - CC=gcc-6
  - CC=clang-3.8

script:
  - scripts/travis-ci-deps.sh
  - eval $(scripts/travis-ci-deps.sh --printenv)
  - ./bootstrap
  - ./configure --with-exec --with-ssh --with-mrsh --with-genders --with-dshgroups --with-netgroup --with-machines
  - make -j 2 check
